name: Frontend CI/CD

on:
  push:
    branches:
      - main
      
permissions:
  contents: read
  actions: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Frontend Image
        run: |
          docker build -t sameerei/technohub-frontend:latest .
          docker push sameerei/technohub-frontend:latest

      - name: Trigger Infra Deployment
        run: |
          set -e
          curl -X POST \
            -H "Authorization: token ${{ secrets.INFRA_TRIGGER_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/Sameer-El/technohub-deployment-infra/dispatches \
            -d '{"event_type":"deploy"}'
